name: Deploy to GitHub Pages
# https://docs.evidence.dev/deployment/self-host/github-pages/ 

on:
  workflow_dispatch:
  push:
    branches: 'main' # or whichever branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: dashboard/package-lock.json

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          uv-version: "latest"

      - name: Install dependencies
        run: uv sync

      - name: Extract FX data
        run: uv run python extract.py

      - name: Copy database
        run: cp -f duckdb.db dashboard/

      - name: Install dependencies
        run: | 
          cd dashboard
          npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          ## Add and uncomment any environment variables here
          ## EVIDENCE_SOURCE__my_source__username: ${{ secrets.EVIDENCE_SOURCE__MY_SOURCE__USERNAME }}
          ## EVIDENCE_SOURCE__my_source__private_key: ${{ secrets.EVIDENCE_SOURCE__MY_SOURCE__PRIVATE_KEY }}
        run: |
          cd dashboard
          npm run sources
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/${{ github.event.repository.name }}'
          #path: 'build'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
